### ISSUE TITLE
Invalid link in the javamopDockerfile

### ISSUE THREAD

**Issue by xyliu-cs** [SoftEngResearch/tracemop#21]
Hi, I've noticed that there's an invalid link in the _scripts/javamopDockerfile_ at line 39:
`wget http://mirrors.ibiblio.org/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz`
It returns **404 Not Found** and prevents users from setting up TraceMop automatically via docker.

For your reference, I have changed the download link to [https://archive.apache.org/dist/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz](url) and successfully set up TraceMop on my machine. You may consider replacing it with this link.

**Comment by owolabileg** [comment]
Thanks a lot for finding this, @xyliu-cs ! 

Could you please open a pull request that fixes this problem?

**Comment by xyliu-cs** [comment]
Sure! No problem.
