### ISSUE TITLE
JavaMOP Parser Misinterprets "to" as a Keyword Instead of an Identifier

### ISSUE THREAD

**Issue by xyliu-cs** [SoftEngResearch/tracemop#24]
Hi, I recently encountered an issue with JavaMOP where the parser seems to misinterpret "to" as a keyword instead of a variable name. The error occurred when I included the `Arrays_SortBeforeBinarySearch.mop` spec to make the agent . The error message I received is attached as `error_trace.txt` for your reference. [error_trace.txt](https://github.com/SoftEngResearch/tracemop/files/11928737/error_trace.txt)

Personally, I addressed this issue by changing all the "to"s into "dest"s as the variable names, but I think you may also check the parser logic to see this problem. 

Thank you and Look forward to your reply.

Best

**Comment by owolabileg** [comment]
The interpretation is correct, as "to" is now a Java identifier.

I suspect that you are using an older set of specs than the ones in this repo's [props](https://github.com/SoftEngResearch/tracemop/tree/master/scripts/props) directory. If so, it is up to you to update them.
